### ISSUE TITLE
Game crashes (Unable to find file /mods/ui-festival/modules/main.lua)

### ISSUE THREAD

**Issue by Androish** [b2ag/ui-festival#3]
I tried to use this now after the Dual screen mod I've been using has an annoying bugmafter the last patch . Cant immidiatly kill units for some wierd reason)

But this crashes when I launch the game? No other mods active.

**Comment by b2ag** [comment]
Can you provide a full log file? Check [this wiki page](http://wiki.faforever.com/index.php?title=Reporting_Technical_Issues) for log file location, but I can't say how up-to-day it is as I play on Linux. I'll have access to my desktop system tomorrow night and will see if it also crashes for me after the last update.

**Comment by Androish** [comment]
Here is the crash file I get like a popup when it crashes: https://pastebin.com/nhDDQ0Uy

Here is the game log:
[game.log](https://github.com/b2ag/ui-festival/files/1350178/game.log)

**Comment by b2ag** [comment]
Hi, it looks like your mod folder is named `ui-festival-master`, probably because it's the git master branch of `ui-festival` and the folder inside the github zip download is called that way. Anyways, you need to rename the folder from `ui-festival-master` to `ui-festival` for the mod to work.

**Comment by Androish** [comment]
Thanks that worked, And the mod seems to work pretty perfectly! I can finally change so that my left screen does not have a 1920*1200 window on a 1080p screen :) (not that much important info got lost down there anyways but still sweet)
